### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by RahulARanger** [RahulARanger/ToolKit#1]
*  **TOPIC**:
creating a python application that uses twitter API

*  **USES**:
 We can create posts using that API using a script.
_ And many more will be added soon._
@mp329  please add more uses idk much.

**Condition**:
* Use Class for the whole script
* Easy to understand
* Good indentation
*Include Comments Please

**Milestone**:
* Create the raw script quickly so that we can think about the GUIS conveniently.

**Comment by mp329** [comment]
Yup

**Comment by RahulARanger** [comment]
excluded
