### ISSUE TITLE
Home Window of the App.

### ISSUE THREAD

**Issue by RahulARanger** [RahulARanger/ToolKit#5]
<h1>Suggestion Needed</h1>

<p>
Since we are doing this Toolkit.
<br>
@mp329 
We have say, x number of tools we have to arrange them like boxes in one window

<b>After that how do we allow users to select among them. I had some ideas</b>

Some of them are:
<ol>
<li> If the user selects any one of the tools from the main window, it will open in another window (like open in new another window on clicking the links)
</li>

<li> If the user selects any of the tools he will open in the same window (like just clicking on the same link)</li>

<li> Another method is like the open in a new tab where we have new tab buttons (like chrome) so if the user clicks anyone we can open that in the new tab
</li>

<li> Please suggest your ways/ideas too</li>
</ol>

<h2>Why am i Asking ?</h2>
<hr>

* even if we try to make modules one by one we have to think how will overall app works

* If we proceed with any of the above methods we may need some extra knowledge

* I have a general idea of those things(mentioned above) exist but I can't implement them fully so if we restrict to any few layouts or ideas. we can easily prepare

* Main: if I didn't write this now I may forget it

<hr>

<h3> Take your own time. If you have any ideas like some designs or tools to add, share it with me too.

**Comment by mp329** [comment]
Must proceed with option 2, as multiple modules are just irritating for many and it should be user friendly. However it also have drawbacks like unable to do multiple tasking and we need to consider that, if we want multitasking we need to drop option 2. Since it is for ca purpose so i would rather say keep it simple.

**Comment by RahulARanger** [comment]
@mp329 
Yes, it would take time for both learning and implementing multitasking in our app.
And it is easy with option 2.

We will proceed with option 2 so every tool needs a back button to redirect the user to the homepage.
